const OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions";

const DEFAULT_OPENROUTER_MODEL = "xiaomi/mimo-v2-flash";
const DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434";
const DEFAULT_OLLAMA_MODEL = "llama3";
const DEFAULT_CONVENTIONAL_FORMAT = "{type}: {msg}";

const CONFIG_KEY_API_KEY = "COMMIAT_OPENROUTER_API_KEY";
const CONFIG_KEY_OPENROUTER_MODEL = "COMMIAT_OPENROUTER_MODEL";
const CONFIG_KEY_USE_OLLAMA = "COMMIAT_USE_OLLAMA";
const CONFIG_KEY_OLLAMA_BASE_URL = "COMMIAT_OLLAMA_BASE_URL";
const CONFIG_KEY_OLLAMA_MODEL = "COMMIAT_OLLAMA_MODEL";
const CONFIG_KEY_OLLAMA_FALLBACK = "COMMIAT_OLLAMA_FALLBACK_TO_OPENROUTER";
const CONFIG_KEY_DEFAULT_MULTI = "COMMIAT_DEFAULT_MULTI";

const STATE_KEY_LEAD_PROMPTED = "LEAD_PROMPTED";
const STATE_KEY_LEAD_PROMPTED_AT = "LEAD_PROMPTED_AT";
const STATE_KEY_LEAD_PROMPTED_SUCCESS = "LEAD_PROMPTED_SUCCESS";

module.exports = {
  OPENROUTER_API_URL,
  DEFAULT_OPENROUTER_MODEL,
  DEFAULT_OLLAMA_BASE_URL,
  DEFAULT_OLLAMA_MODEL,
  DEFAULT_CONVENTIONAL_FORMAT,
  CONFIG_KEY_API_KEY,
  CONFIG_KEY_OPENROUTER_MODEL,
  CONFIG_KEY_USE_OLLAMA,
  CONFIG_KEY_OLLAMA_BASE_URL,
  CONFIG_KEY_OLLAMA_MODEL,
  CONFIG_KEY_OLLAMA_FALLBACK,
  CONFIG_KEY_DEFAULT_MULTI,
  STATE_KEY_LEAD_PROMPTED,
  STATE_KEY_LEAD_PROMPTED_AT,
  STATE_KEY_LEAD_PROMPTED_SUCCESS,
};
